export const SKILL_KEYWORDS = [
  'javascript',
  'typescript',
  'node.js',
  'node',
  'express',
  'react',
  'next.js',
  'redux',
  'html',
  'css',
  'tailwind',
  'bootstrap',
  'java',
  'spring boot',
  'python',
  'django',
  'flask',
  'sql',
  'postgresql',
  'mysql',
  'mongodb',
  'redis',
  'prisma',
  'git',
  'github',
  'docker',
  'kubernetes',
  'aws',
  'azure',
  'gcp',
  'rest api',
  'graphql',
  'socket.io',
  'jest',
  'vitest',
  'c++',
  'c',
  'data structures',
  'algorithms',
  'machine learning',
  'nlp',
  'pandas',
  'numpy'
];

export const ROLE_SKILL_MAP: Record<string, string[]> = {
  'Full Stack Developer': ['react', 'node.js', 'typescript', 'sql', 'rest api'],
  'Backend Developer': ['node.js', 'express', 'sql', 'postgresql', 'rest api'],
  'Frontend Developer': ['react', 'javascript', 'html', 'css', 'typescript'],
  'Software Engineer': ['java', 'python', 'data structures', 'algorithms', 'git'],
  'Data Analyst': ['python', 'sql', 'pandas', 'numpy'],
  'Machine Learning Engineer': ['python', 'machine learning', 'nlp', 'numpy']
};
